<<<<<<< HEAD

name: Java CI with Maven
on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin' # AdoptOpenJDK's build
        cache: 'maven' # Caches Maven dependencies to speed up workflow

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Test with Maven
      run: mvn -B test --file pom.xml
=======
name: Java CI with Maven

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin' # AdoptOpenJDK's build
        cache: 'maven' # Caches Maven dependencies to speed up workflow

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Test with Maven
      run: mvn -B test --file pom.xml
>>>>>>> 08ebfd49d4505c384c09bf7f194fd61f24e0af6f
